name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - name: Format
        run: test -z "$(find . -name '*.go' -not -path './vendor/*' -exec gofmt -l {} +)"
      - name: Test
        run: go test ./...
      - name: Race test
        run: go test -race ./...
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./cmd/cf-redirect
